### ISSUE TITLE
Not able to access global object

### ISSUE THREAD

**Issue by vivekdhiman** [arunpatidar02/aem63app-repo#1]
Hi,

I have one issue in this servlet, global objects are not working in this code snippet.
Such as i am unable to get the current page object in this servlet.
https://github.com/arunpatidar02/aem63app-repo/blob/master/java/HelloWorldCompDDServlet.java

**Comment by arunpatidar02** [comment]
Global object only with WCMUsePojo class. To get current page inside servlet you need to adapt or get from current resource/request.
