### ISSUE TITLE
EmailException

### ISSUE THREAD

**Issue by ravitechoutss** [arunpatidar02/aem63app-repo#4]
getting this exception : org.apache.commons.mail.EmailException: Invalid message supplied

**Comment by arunpatidar02** [comment]
The issue was due to an empty line missing in the template, adding an empty line at the top fixed the issue.
More info https://aemlab.blogspot.com/2019/06/aem-custom-templated-email.html
https://github.com/arunpatidar02/aem63app-repo/commit/55473de38bb620dd0a534456fbf51f7122ddb1ec
